### ISSUE TITLE
Spaces in logpath paths causing errors on start

### ISSUE THREAD

**Issue by sibrcode** [beezwax/filemaker-fail2ban#3]
Previously, with OS X and fail2ban version 0.93, a path such as this would work:

`logpath  = /Library/FileMaker Server/Logs/Event.log`

However, with fail2ban 0.93 on El Capitan I now get:

```
# fail2ban-client -d
ERROR  No file(s) found for glob /Library/FileMaker
ERROR  Failed during configuration: Have not found any log file for filemaker-client jail
Traceback (most recent call last):
  File "/opt/local/bin/fail2ban-client", line 470, in <module>
    if client.start(sys.argv):
  File "/opt/local/bin/fail2ban-client", line 403, in start
    self.dumpConfig(self.__stream)
  File "/opt/local/bin/fail2ban-client", line 459, in dumpConfig
    for c in cmd:
TypeError: 'NoneType' object is not iterable
```

A hack around this is to create a symlink in /var/log to FileMaker's Log folder, and use that path for the logpath.

**Comment by sibrcode** [comment]
Although I couldn't get confirmation, this appears to be the case in any version 0.9 of fail2ban. May also be affecting the ability to include related log lines in emails.

Fixed by adding directions in README.md to create an alias to the FileMaker Server folder without a space in its name.
